### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by pastacook** [pastacook/protospace-38339#1]
https://protospace-38339.onrender.com/

**Comment by pastacook** [comment]
ご指摘ありがとうございます。修正して再度render上でもデプロイしました。
（再度Googleフォームを提出します）

**Comment by motomuun** [comment]
@pastacook さん、再度ご提出頂きありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
